version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
      - REACT_APP_AUTH_DOMAIN=${REACT_APP_AUTH_DOMAIN}
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - FIREBASE_ADMIN_TYPE=${FIREBASE_ADMIN_TYPE}
      - FIREBASE_ADMIN_PROJECT_ID=${FIREBASE_ADMIN_PROJECT_ID}
      - FIREBASE_ADMIN_PRIVATE_KEY_ID=${FIREBASE_ADMIN_PRIVATE_KEY_ID}
      - FIREBASE_ADMIN_PRIVATE_KEY=${FIREBASE_ADMIN_PRIVATE_KEY}
      - FIREBASE_ADMIN_CLIENT_EMAIL=${FIREBASE_ADMIN_CLIENT_EMAIL}
      - FIREBASE_ADMIN_CLIENT_ID=${FIREBASE_ADMIN_CLIENT_ID}
      - FIREBASE_ADMIN_AUTH_URI=${FIREBASE_ADMIN_AUTH_URI}
      - FIREBASE_ADMIN_TOKEN_URI=${FIREBASE_ADMIN_TOKEN_URI}
      - FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL}
      - FIREBASE_ADMIN_CLIENT_X509_CERT_URL=${FIREBASE_ADMIN_CLIENT_X509_CERT_URL}
    depends_on:
      - db

  db:
    image: 'mongo:latest'
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongodb_data:
